---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "if-db"
  namespace: "default"
  labels:
    app: "if-db"
spec:
  ports:
  - protocol: "TCP"
    port: 27017
    targetPort: 27017
  selector:
    app: "if-db"
---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "if-db"
  namespace: "default"
  labels:
    app: "if-db"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "if-db"
  template:
    metadata:
      labels:
        app: "if-db"
    spec:
      containers:
      - name: "mongo"
        image: "mongo:3.6"
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "if-app-service"
  namespace: "default"
  labels:
    app: "if-app"
spec:
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  selector:
    app: "if-app"
  type: "LoadBalancer"
---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "if-app"
  namespace: "default"
  labels:
    app: "if-app"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "if-app"
  template:
    metadata:
      labels:
        app: "if-app"
    spec:
      containers:
      - name: "digitalengineeringcourse"
        image: "capcotomaa/digitalengineeringcourse2:latest"

